version: '3.8'
services:
  backend:
    image: ${BACKEND_IMAGE:-geass/helixauth-backend:latest}
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/helix
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-dev}
    depends_on:
      - db
#      - redis
  frontend:
    image: ${FRONTEND_IMAGE:-geass/helixauth-frontend:latest}
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: helix
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
    volumes:
      - /mnt/db_volume_nyc1_01:/var/lib/postgresql/data
    ports:
      - "5432:5432"
#  redis:
#    image: redis:latest
#    # Remove the ports line to prevent Redis from being accessible from outside the Docker network
#    command: redis-server --requirepass Helix!123!Auth
#    networks:
#      - internal
#
## Define the internal network
#networks:
#  internal:
#    driver: bridge
