# Build Stage
FROM node:14 AS build
WORKDIR /app
COPY frontend/package.json frontend/package-lock.json* ./
RUN yarn add
COPY frontend/ .
RUN yarn start

# Serve Stage
FROM nginx:stable
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
