# Use a base image with both Java and Gradle installed
FROM gradle:7.6.4-jdk11-jammy as builder

# Set the working directory inside the container
WORKDIR /app

# Copy the Gradle Kotlin DSL configuration files separately
COPY build.gradle.kts settings.gradle.kts gradlew /app/
COPY gradle /app/gradle

# Only download dependencies
# Avoids re-downloading them unless dependencies change
RUN gradle --no-daemon --console plain dependencies

# Copy the rest of the application
COPY src /app/src

# Build the application
RUN gradle --no-daemon --console plain build -x test

# Second stage: copy the build artifact from the previous stage
FROM openjdk:11-jre-slim

# VOLUME instruction to indicate that /tmp should be a mount point
VOLUME /tmp

# Expose the port the app runs on
EXPOSE 8080

# Copy the jar from the builder stage to this new stage
COPY --from=builder /app/build/libs/helixauth-0.0.1-SNAPSHOT.jar app.jar

# Set the container entry point
ENTRYPOINT ["java", "-jar", "/app.jar"]
