CREATE TABLE IF NOT EXISTS company (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    phone VARCHAR(255),
    street VARCHAR(255),
    city VARCHAR(255),
    state VARCHAR(255),
    zip INTEGER,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(255),
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255),
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    avatar VARCHAR(255),
    company_id BIGINT,
    PRIMARY KEY (id),
    FOREIGN KEY (company_id) REFERENCES company (id)
);

CREATE TABLE IF NOT EXISTS api_key (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    key VARCHAR(255) NOT NULL,
    company_id BIGINT,
    PRIMARY KEY (id),
    FOREIGN KEY (company_id) REFERENCES company (id)
);

CREATE TABLE IF NOT EXISTS endpoint_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    path VARCHAR(255) NOT NULL,
    operation VARCHAR(255) NOT NULL,
    company_id BIGINT,
    PRIMARY KEY (id),
    FOREIGN KEY (company_id) REFERENCES company (id)
);

CREATE TABLE IF NOT EXISTS role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS endpoint_config_role (
    endpoint_config_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (endpoint_config_id, role_id),
    FOREIGN KEY (endpoint_config_id) REFERENCES endpoint_config (id),
    FOREIGN KEY (role_id) REFERENCES role (id)
);

INSERT INTO company (name, phone, street, city, state, zip)
VALUES ('Test Company', '1234567890', '1234 Test St', 'Testville', 'TestState', '12345')
ON CONFLICT (name) DO NOTHING;

-- Assuming 'email' is a unique identifier for 'users'
INSERT INTO users (username, email, password, first_name, last_name, avatar, company_id)
VALUES
('user1', 'user1@test.com', 'password', 'User', 'One', 'avatar1.png', 1),
('user2', 'user2@test.com', 'password', 'User', 'Two', 'avatar2.png', 1),
('user3', 'user3@test.com', 'password', 'User', 'Three', 'avatar3.png', 1)
ON CONFLICT (email) DO NOTHING;

-- Assuming 'key' is a unique identifier for 'api_key'
INSERT INTO api_key (key, company_id)
VALUES ('abcd1234efgh5678', 1)
ON CONFLICT (key) DO NOTHING;

-- For 'role', assuming 'name' is unique
INSERT INTO role (name)
VALUES ('Admin'), ('Editor'), ('Viewer')
ON CONFLICT (name) DO NOTHING;

-- For 'endpoint_config', assuming path+operation+company_id combination is unique
INSERT INTO endpoint_config (path, operation, company_id)
VALUES
('/api/data', 'GET', 1),
('/api/data', 'POST', 1),
('/api/user', 'GET', 1),
('/api/user', 'POST', 1),
('/api/user/{id}', 'DELETE', 1)
ON CONFLICT (path, operation, company_id) DO NOTHING;

-- 'endpoint_config_role' doesn't need a unique key outside of its PK, which is typically auto-generated
INSERT INTO endpoint_config_role (endpoint_config_id, role_id)
VALUES
(1, 1),
(2, 1),
(3, 1),
(4, 1),
(5, 1),
(2, 2),
(4, 2),
(1, 3),
(3, 3)
ON CONFLICT DO NOTHING;
