name: Build and Deploy

on:
  push:
    branches:
      - master
      - dev  # Trigger on pushes to master and dev branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set up Node.js and Yarn
        uses: borales/actions-yarn@v2
        with:
          yarn-version: 1.x
          node-version: 14.x

      - name: Install dependencies
        run: yarn install

      - name: Build frontend
        run: yarn build

      - name: Set up Kotlin
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build backend
        run: cd backend && ./gradlew build

      - name: Run backend and database
        run: |
          echo "Running backend and database"
          java -jar backend/build/libs/helixauth.jar &
          # Run your database, e.g., `docker-compose up -d` or any other command to start your database

      - name: Deploy application
        run: |
          echo "Deploying application"
          # Deploy frontend, backend, and database
          # For example:
          # rsync -avz --delete frontend/build/ helix_dev@helix-ubuntu-s-2vcpu-4gb-120gb-intel-nyc1-01:/path/to/production/frontend
          # rsync -avz --delete backend/build/libs/helixauth.jar helix_dev@helix-ubuntu-s-2vcpu-4gb-120gb-intel-nyc1-01:/path/to/production/backend