name: Build and Deploy Workflow

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

  deploy_master:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Deploy to Production server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_USERNAME }}
          key: ${{ secrets.PRODUCTION_SSH_PRIVATE_KEY }}
          script: |
            cd ~/helixauth
            
            # Pull the latest changes from the repository
            git pull origin master

            # Build the application using Gradle
            chmod +x ./gradlew
            ./gradlew clean build

            # Commands to stop and start the Docker application
            docker-compose down
            sleep 10
            docker-compose up --build -d

  deploy_dev:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Deploy to Development server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          script: |
            cd ~/devhelixauth
            
            # Pull the latest changes from the repository
            git pull origin dev

            # Build the application using Gradle
            chmod +x ./gradlew
            ./gradlew clean build

            # Commands to stop and start the Docker application
            docker-compose down
            sleep 10
            docker-compose up --build -d
