name: Build and Deploy Workflow

on:
  push:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
          matrix:
            include:
              - component: backend
                dockerfile: docker/Dockerfile-backend
              - component: frontend
                dockerfile: docker/Dockerfile-frontend
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/helixauth-${{ matrix.component }}:${{ github.sha }}

  deploy_dev:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Copy files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          source: "./docker-compose.yml"
          target: "/var/www/dev.helixauth.com/docker-compose.yml"

      - name: Deploy to Development Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          script: |
            # Set environment variables for the Docker image tags
            BACKEND_TAG=${{ github.sha }}
            FRONTEND_TAG=${{ github.sha }}

            # Export these variables to be used by docker-compose
            export BACKEND_TAG
            export FRONTEND_TAG

            # Restart the applications using Docker Compose
            # Assuming docker-compose.yml uses environment variables for image tags
            cd /var/www/dev.helixauth.com
            docker-compose down
            docker-compose up --build -d
