name: Build and Deploy Workflow [PROD]

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
          matrix:
            include:
              - component: backend
                dockerfile: docker/Dockerfile-backend
              - component: frontend
                dockerfile: docker/Dockerfile-frontend
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine the Docker Tag
        id: docker_tag
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "::set-output name=tag::${GITHUB_REF/refs\/tags\//}"
          else
            echo "::set-output name=tag::${GITHUB_SHA}"
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/helixauth-${{ matrix.component }}:${{ steps.docker_tag.outputs.tag }}

  deploy_prod:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Copy files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          source: "./docker-compose.yml"
          target: "/var/www/prod.helixauth.com/"

      - name: Deploy to Prodelopment Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          script: |
            # Set environment variables for the Docker image tags
            BACKEND_TAG=${{ steps.docker_tag.outputs.tag }}
            FRONTEND_TAG=${{ steps.docker_tag.outputs.tag }}

            # Set the Docker image names
            BACKEND_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/helixauth-backend:${BACKEND_TAG}
            FRONTEND_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/helixauth-frontend:${FRONTEND_TAG}

            # Export these variables to be used by docker-compose
            export BACKEND_IMAGE
            export FRONTEND_IMAGE

            # Restart the applications using Docker Compose
            # Assuming docker-compose.yml uses environment variables for image tags
            cd /var/www/prod.helixauth.com
            docker compose down
            docker compose up --build -d
