name: Renew Certs

# Controls when the workflow will run
on:
  # Triggers the workflow on a timer. This particular timer runs on the first day of the month. CertBot certs are renewable every 30 days, so this should work for that purpose.
  schedule:
    - cron:  '0 5 */31 * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  renew_certs:
    env: 
      DO_TOKEN: ${{ secrets.DO_TOKEN }}
    name: Modifiy repository files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.2
      - name: Run the scipt
        working-directory: ${{env.working-directory}}
        run: |          
          ./.github/workflows/scripts/renew_certs.sh