name: Renew Certs

on:
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  renew_certs:
    name: Modifiy repository files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.2
      - name: Run the scipt
        working-directory: ${{env.working-directory}}
        run: |          
          ls -la